name: Android APK Build RedHat

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Login to Red Hat registry
      - name: Login to Red Hat Registry
        run: |
          echo "${{ secrets.REDHAT_REGISTRY_PASSWORD }}" | docker login registry.redhat.io \
            -u "${{ secrets.REDHAT_REGISTRY_USERNAME }}" --password-stdin

      # Build Docker image (from registry.redhat.io)
      - name: Build Android Build Image
        run: |
          docker build -t android-builder .

      # Run Gradle build inside container
      - name: Build APK
        run: |
          docker run --rm \
            -v $HOME/.gradle:/root/.gradle \
            -v ${{ github.workspace }}:/app \
            -w /app \
            android-builder gradle assembleRelease 

      # Upload APK artifact
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: '**/build/outputs/apk/release/*.apk'
